# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='alcohol',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='bathrooms',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='coffee',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Truck Stop'), (2, 'Good'), (3, 'Really Good'), (4, 'Great')], null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='food',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='outdoor',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='outlets',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Minimal'), (2, 'Some'), (3, 'Ample')], null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='seating',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Minimal'), (2, 'Some'), (3, 'Ample')], null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='wifi',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Spotty'), (2, 'Strong')], null=True),
        ),
    ]
