# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 09:27
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160718_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
