# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_location_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steaming_url_high', models.TextField(blank=True, null=True)),
                ('steaming_url_low', models.TextField(blank=True, null=True)),
                ('thumb_720', models.TextField(blank=True, null=True)),
                ('thumb_180', models.TextField(blank=True, null=True)),
                ('thumb_64', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
