# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='steaming_url_high',
            new_name='streaming_url_high',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='steaming_url_low',
            new_name='streaming_url_low',
        ),
    ]
